### ISSUE TITLE
torch lr_schedulers not accepted

### ISSUE THREAD

**Issue by TomasGadea** [LEFTeyex/warmup#1]
When instantiating the object `WarmUpScheduler` and passing e.g. the `torch.optim.lr_scheduler.CosineAnnealingLR` as in `example.py` execution fails due to the following error: 

```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    warmup_scheduler = WarmUpScheduler(optimizer, lr_scheduler,
  File "/Users/tomas.gadea/Desktop/test/env/lib/python3.8/site-packages/warmup_scheduler_pytorch/warmup_module.py", line 52, in __init__
    raise TypeError(f'{type(lr_scheduler).__name__} is not a lr_scheduler in pytorch')
TypeError: CosineAnnealingLR is not a lr_scheduler in pytorch
```

It does not work for any of the typical torch schedulers.

**Comment by LEFTeyex** [comment]
What is the version of your pytorch？

**Comment by shlyahin** [comment]
> What is the version of your pytorch？

I have the same error. Torch 2.0.1

**Comment by Forbu** [comment]
@shlyahin I check the code : we need to make add "LRScheduler" in the list of attribute available here : 
https://github.com/LEFTeyex/warmup/blob/f90a3525bd69b1c50964e24bb871924d984ded7f/src/warmup_scheduler_pytorch/warmup_module.py#L51

```python
if not isinstance(lr_scheduler, (_LRScheduler, ReduceLROnPlateau)):
```

```python
if not isinstance(lr_scheduler, (_LRScheduler, LRScheduler, ReduceLROnPlateau)):
```

**Comment by Forbu** [comment]
but it's for torch 2.0

**Comment by LEFTeyex** [comment]
I will update the code soon to adapt to the new version of PyTorch.
